# Generated by Django 2.1 on 2018-11-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foresite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
